common:
    authorization_header: 'Basic d3UxMGkxVS1xS2IwdVlWLXAwNWxabmpjbGhjcE1uV2c1ZHFROWZ4dHNjczpGLXpkQzlGRU45Sl8wVFJ2SmV1NS1yYnVBX1MxZ3pmbnNWMm9rRkJDRS1F'
    nacta_api_host: 'https://open.nacta.edu.cn'
    nacta_sync_url: '/broadcast/door_event'
    nacta_auth_url: '/oauth/token'
kafka:
    bootstrap_servers: '127.0.0.1:9092'
    group_id: 'door-lock-sync'
    schema_registry_url: 'http://127.0.0.1:18081'
    topics: 'roomis-door_lock_sync'
    retry_seconds: 100
    batch_size: 30